version: "3.8"
services:
  dataingestion_service:
    build: 
      context: #input file location 
      dockerfile: Dockerfile
    ports:
      - "501:500"
  
  featureextraction_service:
    build: 
      context: #input file location
      dockerfile: Dockerfile
    depends_on:
      - dataingestion_service
    ports:
      - "502:500"

  
  training_service:
    build: 
      context: #input file location 
      dockerfile: Dockerfile
    depends_on:
      featureextraction_service
    ports:
      - "503:500"

  predict_service:
    build: 
      context: #input file location
      dockerfile: Dockerfile
    depends_on:
      training_service
    ports:
      - "504:500"
    
  visualization_service:
    build: 
      context: #input file location 
      dockerfile: Dockerfile  
    depends_on:
      predict_service
    ports:
      - "505:500"



