version: "3.8"
services:
  dataingestion_service:
    build: 
      context: #input file location 
      dockerfile: Dockerfile
    ports:
      - "501:500"
    enviroment:
      - TRAININGDB_API = http://dataingestion_service:500/DataIngestion/database
  
  featureextraction_service:
    build: 
      context: #input file location
      dockerfile: Dockerfile
    depends_on:
      - dataingestion_service
    ports:
      - "502:500"
    enviroment:
      - TRAININGDB_API = http://dataingestion_service:500/DataIngestion/database
  
  
  training_service:
    build: 
      context: #input file location 
      dockerfile: Dockerfile
    depends_on:
      featureextraction_service
    ports:
      - "503:500"
    environment:
      - FEATURE_API = http://featureextraction_service:500/2.FeatureExtractions/DatabaseFeatures

  predict_service:
    build: 
      context: #input file location
      dockerfile: Dockerfile
    depends_on:
      training_service
    ports:
      - "504:500"
    enviroment:
      - MODEL_API = http://training_service:500/Training/model
    
  visualization_service:
    build: 
      context: #input file location 
      dockerfile: Dockerfile  
    depends_on:
      predict_service
    ports:
      - "505:500"




