#using python as base image
FROM python:3.9-slim
#set work directory
WORKDIR /myapp
# Get all files in this directory
COPY . .
#install packages
RUN pip install --no-cache-dir -r requirements.txt

#expose to port 500
EXPOSE 500
# define URL needed for Feature extraction
# TEST
CMD ["python" ,"app.py"] 