version: "3.8"
services:
  dataingestion_service:
    build: 
      context: ./../ContainerizationAssigment/1.DataIngestion
      dockerfile: Dockerfile
    ports:
      - "501:500"
    
  featureextraction_service:
    build: 
      context: ./../ContainerizationAssigment/2.FeatureExtractions
      dockerfile: Dockerfile
    depends_on:
      - dataingestion_service
    ports:
      - "502:500"
    environment:
      - TRAININGDB_API=http://dataingestion_service:500/DataIngestion/database
  
  
  training_service:
    build: 
      context: ./../ContainerizationAssigment/3.Training
      dockerfile: Dockerfile
    depends_on:
      - featureextraction_service
    ports:
      - "503:500"
    environment:
      - FEATURE_API=http://featureextraction_service:500/2.FeatureExtractions/DatabaseFeatures
      - Model_Repo=/myapp/models

  predict_service:
    build: 
      context: ./../ContainerizationAssigment/4.Predict
      dockerfile: Dockerfile
    depends_on:
      - training_service
    ports:
      - "504:500"
    environment:
      - Train_API=http://training_service:500/Training/model
      - Model_Repo=/myapp/models
#    
#  visualization_service:
#    build: 
#      context: ./../ContainerizationAssigment/5.Visualization 
#      dockerfile: Dockerfile  
#    depends_on:
#      - predict_service
#    ports:
#      - "505:500"




