version: "3.8"
services:
  dataingestion_service:
    build: 
      context: ./../ContainerizationAssigment/1.DataIngestion
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    
  featureextraction_service:
    build: 
      context: ./../ContainerizationAssigment/2.FeatureExtractions
      dockerfile: Dockerfile
    depends_on:
      - dataingestion_service
    ports:
      - "5002:5000"
    environment:
      - TRAININGDB_API=http://dataingestion_service:5000/DataIngestion/database
  
  
  training_service:
    build: 
      context: ./../ContainerizationAssigment/3.Training
      dockerfile: Dockerfile
    depends_on:
      - featureextraction_service
    ports:
      - "5003:5000"
    environment:
      - FEATURE_API=http://featureextraction_service:5000/2.FeatureExtractions/DatabaseFeatures
      - MODEL_REPO=/myapp/models
    volumes:
      - "model-repo:/myapp/models"

  predict_service:
    build: 
      context: ./../ContainerizationAssigment/4.Predict
      dockerfile: Dockerfile
    depends_on:
      - training_service
    ports:
      - "5004:5000"
    environment:
      - Train_API=http://training_service:5000/Training/model
      - MODEL_REPO=/myapp/models
    volumes:
      - "model-repo:/myapp/models"
    
  visualization_service:
    build: 
      context: ./../ContainerizationAssigment/5.Visualization 
      dockerfile: Dockerfile  
    depends_on:
      - predict_service
    ports:
      - "5005:5000"

volumes:
  model-repo:




